<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    public function getCategories()
    {
        return response()->json(['data' => Category::all()], 200);
    }

    public function createCategory(Request $request)
    {
        $request->validate(['name' => 'required|string']);

        $category = Category::create([
            'name' => $request->name,
            'description' => $request->input('description'), // optional
            // 'slug' will be auto-generated by model
        ]);

        return response()->json([
            'message' => 'Category created successfully',
            'data' => $category
        ], 201);
    }

    public function getCategory($categoryId)
    {
        $category = Category::find($categoryId);
        if (!$category) return response()->json(['message' => 'Category not found'], 404);

        return response()->json(['data' => $category], 200);
    }

    public function updateCategory(Request $request, $categoryId)
    {
        $category = Category::find($categoryId);
        if (!$category) return response()->json(['message' => 'Category not found'], 404);

        $category->update($request->only(['name', 'description']));

        return response()->json([
            'message' => 'Category updated successfully',
            'data' => $category
        ], 200);
    }

    public function deleteCategory($categoryId)
    {
        $category = Category::find($categoryId);
        if (!$category) return response()->json(['message' => 'Category not found'], 404);

        $category->delete();

        return response()->json(['message' => 'Category deleted successfully'], 200);
    }
}
